version: "2.3"
services:
    search_backend:
        build: .
        ipc: host
        command: "flask run --host=0.0.0.0"
        #volumes:
        #    - .:/develop/
        #command: "tail -F /dev/null"
        environment:
            - DBCONNECT
            - FLASK_APP=app.py
        ports:
            - 5000:5000
