apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "ingestion.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "ingestion.name" . }}
    helm.sh/chart: {{ include "ingestion.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "ingestion.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
              - mountPath: /input
                name: input-volume
          command: ['python3', 'pdf_ingestion.py', '/input']
          env:
              - name: DBCONNECT
                value: "mongodb://{{ .Values.mongouser }}:{{ .Values.mongopwd }}@{{ .Values.mongourl }}:{{ .Values.mongoport }}"
      restartPolicy: Never
      volumes:
          - name: input-volume
            hostPath:
                path: {{ .Values.pdfDir }}
