version: "2.3"
services:
    code_ingestion:
        build: .
        ipc: host
        volumes:
            #    - .:/develop/
            - ${INPUT_DIR}:/input/
        #command: "tail -F /dev/null"
        command: "python3 code_ingestion.py /input 30"
        environment:
            - DBCONNECT

