version: "2.3"
services:
    ingestion:
        build: .
        ipc: host
        volumes:
            - .:/develop/
        command: tail -F anything
        environment:
            - DB_CONNECT="mongodb://sverma25:Cosmos@cosmos0000.chtc.wisc.edu/pdfs:21017?authSource=admin"

