version: "3"

networks:
  default:
    external:
      name: cosmos_swarm_network 
services:
    preprocess:
        image: ankurgos/retrieval:latest
        environment:
            - DATASET_ID
            - MYSQL_USER=myuser
            - MYSQL_DATABASE=cosmos
            - MYSQL_PASSWORD=cosmos123
        volumes:
            - ${DATASET_INDEX_DIR}:/index_dir
        command: "python write_dataset.py"

    index:
        image: ankurgos/retrieval:latest
        environment:
            - DATASET_ID
            - MYSQL_USER=myuser
            - MYSQL_DATABASE=cosmos
            - MYSQL_PASSWORD=cosmos123
        volumes:
            - ${DATASET_INDEX_DIR}:/index_dir
        command: "/bin/bash -c ./index.sh"


    retrieve:
        image: ankurgos/retrieval:latest
        environment:
            - DATASET_ID
        volumes:
            - ${DATASET_INDEX_DIR}:/index_dir

