version: "3"

networks:
  default:
    external:
      name: cosmos_swarm_network 

services:
    extract_tables:
        image: iaross/extract_tables_test:latest
        ipc: host
        command: "python3 -m tableextractions.pdf_table_extractions"
#        command: "tail -f /dev/null"
        volumes:
#            - /hdd/iaross/covid_docs_3Apr/xaa_dir:/input
            - ${DIR}:/input
#            - /home/iaross/test_pdfs/:/input
        environment:
            - DATASET_ID
            - MYSQL_USER=myuser
            - MYSQL_PASSWORD=cosmos123
            - MYSQL_HOST=mysql-server-1
            - MYSQL_PORT=3306
        #networks:
        #    cosmos_swarm_network:
        depends_on:
            - scheduler

    scheduler:
        image: iaross/extract_tables_test:latest
        #networks:
        #    cosmos_swarm_network:
        command: "dask-scheduler --port 8788"
        ports:
            - 8786:8786
#
    worker1:
        image: iaross/extract_tables_test:latest
        environment:
            - MYSQL_USER=myuser
            - MYSQL_PASSWORD=cosmos123
            - MYSQL_HOST=mysql-server-1
            - MYSQL_PORT=3306
            - CUDA_VISIBLE_DEVICES=''
        command: "dask-worker tcp://scheduler:8788 --nprocs 16 --resources 'extract_tables=1'"
        depends_on:
            - scheduler
#
#
