version: "3.4"
networks:
    swarm_network:
        external: 
            name: cosmos_swarm_network

services:
    frontend:
        build: .
        volumes:
            - './cosmos:/app/'
            - '/app/node_modules'
        command: "yarn start"
        ports:
            - 3001:3000

        networks:
            swarm_network:



