version: '3.4'

networks:
  cosmos_swarm_network:
    external: true

services:
  upload:
    image: ${UPLOAD_IMAGE}
    environment:
      - ELASTIC_ADDRESS
    networks:
      cosmos_swarm_network:
    volumes:
      - ${OUTPUT_DIR}:/output
