version: '3'
networks:
    cosmos_swarm_network:
        external: true
services:
  create_schema:
    networks:
        cosmos_swarm_network:
    env_file:
      - schema.env
    image: schema:latest
    command: python schema.py

  create_sqlite:
    networks:
        cosmos_swarm_network:
    env_file:
      - schema.env
    volumes:
        - ./:/db
    image: schema:latest
    command: python schema.py --sqlite

  migrate:
    networks:
        cosmos_swarm_network:
    env_file:
      - schema.env
    image: schema:latest
    command: alembic upgrade head

