version: '3'
networks:
  default:
    external:
      name: cosmos_swarm_network 

services:
  create_schema:
    env_file:
      - schema.env
    image: schema:latest
    command: python schema.py

  migrate:
    env_file:
      - schema.env
    image: schema:latest
    command: alembic upgrade head

  downgrade:
    env_file:
      - schema.env
    image: schema:latest
    command: alembic downgrade -1 
