version: '3'
networks:
  default:
    external:
      name: cosmos_swarm_network 

services:
  create_schema:
    env_file:
      - schema.env
    image: schema:latest
    command: python schema.py

  create_sqlite:
    networks:
        cosmos_swarm_network:
    env_file:
      - schema.env
    volumes:
        - ./:/db
    image: schema:latest
    command: python schema.py --sqlite

  migrate:
    env_file:
      - schema.env
    image: schema:latest
    command: alembic upgrade head

  downgrade:
    env_file:
      - schema.env
    image: schema:latest
    command: alembic downgrade -1 
