version: '2.3'
services:
  ingest_elastic:
      build: .
      ipc: host
      command: "python ingest_elastic.py --no-objects --no-sections --no-code --tables --no-figures --no-equations"
      #volumes:
      #    - .:/develop/
      #command: "tail -F /dev/null"
      environment:
          - DBCONNECT

networks:
  default:
    external:
      name: elasticsearch_esnet
