version: '3'
networks:
  default:
    external:
      name: cosmos_swarm_network 

services:
    word2vec_endpoint:
        build: .
        ipc: host
        container_name: word2vec_endpoint
        command: "flask run --host=0.0.0.0 --port=5003"
        environment:
            - FLASK_APP=app.py
            - FLASK_ENV=development
        ports:
            - 5003:5003
        volumes:
            - ./data:/app/data


