version: "2.3"

services:
    aggregate_sections:
        image: iaross/aggregate_sections_test
        ipc: host
#        volumes:
#            - .:/develop/
#        command: "python3 aggregate.py 1 --section --equation --figure --table"
        command: "python3 aggregate.py 1 --section"
#        command: "tail -f /dev/null"

        environment:
            - MYSQL_USER=myuser
            - MYSQL_DATABASE=cosmos
            - MYSQL_PASSWORD=cosmos123
networks:
  default:
    external:
      name: cosmos_swarm_network 

