version: "3"

networks:
  default:
    external:
      name: cosmos_swarm_network 
services:
    aggregate_sections:
        image: ankurgos/aggregate_sections:latest
        command: "python3 -m agg.aggregate"
        environment:
            - DATASET_ID
            - MYSQL_USER=myuser
            - MYSQL_DATABASE=cosmos
            - MYSQL_PASSWORD=cosmos123
        #networks:
        #    cosmos_swarm_network:
        depends_on:
            - scheduler

    scheduler:
        image: ankurgos/aggregate_sections:latest
        #networks:
        #    cosmos_swarm_network:
        command: "dask-scheduler --port 8786"
        ports:
            - 8788:8787

    worker1:
        image: ankurgos/aggregate_sections:latest
        #networks:
        #    cosmos_swarm_network:
        environment:
            - MYSQL_USER=myuser
            - MYSQL_DATABASE=cosmos
            - MYSQL_PASSWORD=cosmos123
            - CUDA_VISIBLE_DEVICES=''
        depends_on:
            - scheduler
        command: "dask-worker tcp://scheduler:8786 --nprocs 5"
        volumes:
            - ${TMP_DIR}:/tmp


