BACKBONE: "resnet50"
HEAD_DIM: 1024
NHEADS: 3
EMBEDDING_DIM: 256
EMBEDDING_INTERMEDIATE: 1024
PROPOSAL_METHOD: "CONNECTED_COMPONENTS"
WARPED_SIZE: 250
EXPANSION_DELTA: 50
CLASSES: ["Section Header", "Body Text", "Figure", "Figure Caption", "Table", "Equation",
          "Page Footer", "Page Header", "Table Caption", "Other", "Reference text"]
TRAINING: True
