version: "2.3"
services:
    cosmos:
        build: .
        ipc: host
        volumes:
            - .:/develop/
        command: tail -F anything

    cosmos_postgres:
        image: postgres:10.5-alpine
        environment:
            - POSTGRES_DB=cosmos
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
        ports:
            - 54321:5432
