version: "2.3"
services:
    torch_model:
        build: .
        runtime: nvidia
        ipc: host
        volumes:
            - .:/vol/
    redis:
      image: "redis:alpine"
      volumes:
        - ./redis_data:/data
      restart: always
      ports:
        - "6379:6379"

