version: '3.4'

networks:
    swarm_network:
        driver: overlay
        attachable: true

services:
    adminer:
        image: adminer
        ports:
            - 8080:8080
        networks:
            swarm_network:

    mysql-server-1:
      env_file:
        - ./database/innodb-cluster/mysql-server.env
      image: mysql/mysql-server:8.0.12
      networks:
          swarm_network:
      volumes:
          - ${DB_PTH}:/var/lib/mysql
          - ${DB_TMP_PTH}:/tmp
      ports:
        - "3301:3306"
      command: ["mysqld","--server_id=1","--binlog_checksum=NONE","--gtid_mode=ON","--enforce_gtid_consistency=ON","--log_bin","--log_slave_updates=ON","--master_info_repository=TABLE","--relay_log_info_repository=TABLE","--transaction_write_set_extraction=XXHASH64","--user=mysql","--skip-host-cache","--skip-name-resolve", "--default_authentication_plugin=mysql_native_password", "--max-connections=1024", "--innodb_buffer_pool_size=16g", "--group-concat-max-len=4294967295", "--innodb-log-file-size=1G"]

    ingestion:
        image: uwcosmos/ingestion:dev
        networks:
            swarm_network:
        environment:
            - MYSQL_USER
            - MYSQL_PASSWORD
            - MYSQL_HOST
            - MYSQL_PORT
            - DEVICE=cpu
            - PYTHONUNBUFFERED=TRUE
        command: "gunicorn -w 4 -b 0.0.0.0:8000 ingest.app"
        depends_on:
            - scheduler
            - worker1
            - worker2
        ports:
            - 8000:8000

    scheduler:
        image: uwcosmos/ingestion:dev
        networks:
            swarm_network:
        command: "dask-scheduler"
#        ports:
#            - 8787:8787

    worker1:
        image: uwcosmos/ingestion:dev
        networks:
            swarm_network:
        environment:
            - MYSQL_USER
            - MYSQL_PASSWORD
            - MYSQL_HOST
            - MYSQL_PORT
            - CUDA_VISIBLE_DEVICES=''
        command: "dask-worker tcp://scheduler:8786 --nprocs 15 --resources 'process=1' --preload ingest.process_setup"
        volumes:
            - ${TMP_PTH}:/tmp
        depends_on:
            - scheduler

    worker2:
        image: uwcosmos/ingestion:dev
        networks:
            swarm_network:
        environment:
            - MYSQL_USER
            - MYSQL_PASSWORD
            - MYSQL_HOST
            - MYSQL_PORT
            - DEVICE=cpu
            - CUDA_VISIBLE_DEVICES=''
        command: "dask-worker tcp://scheduler:8786 --nprocs 1 --resources 'GPU=1' --preload ingest.detect_setup"
        depends_on:
            - scheduler
              #

    mysql-shell:
        networks:
            swarm_network:
        env_file:
            - ./database/innodb-cluster/mysql-shell.env
        image: neumayer/mysql-shell-batch
        volumes:
            - ./database/innodb-cluster/scripts/:/scripts/
        depends_on:
          - mysql-server-1

    create_schema:
        networks:
            swarm_network:
        environment:
            - MYSQL_USER
            - MYSQL_PASSWORD
            - MYSQL_HOST
            - MYSQL_PORT
        image: uwcosmos/schema:dev
        command: python schema.py

    dbwebapp:
        networks:
            swarm_network:
        environment:
            - DBUSER=${MYSQL_USER}
            - DBPASS=${MYSQL_PASSWORD}
            - DBHOST=${MYSQL_HOST}
            - DBPORT=${MYSQL_PORT}
            - DBNAME=${MYSQL_DATABASE}
        image: neumayer/dbwebapp
        ports:
            - "8089:8080"
        depends_on:
            - mysql-server-1

    gateway:
        networks:
            swarm_network:
        image: uwcosmos/visualizer:dev
        ports:
            - 8081:80
        depends_on:
            - search_backend
  
    search_backend:
        networks:
            swarm_network:
        image: uwcosmos/sbackend:dev
        command: "flask run --host=0.0.0.0 --port=5001"
        ports:
            - 5001:5001
        environment:
            - MYSQL_USER
            - MYSQL_PASSWORD
            - MYSQL_HOST
            - MYSQL_PORT
            - PDF_DB=pdfs
            - FLASK_APP=app.py
            - FLASK_ENV=development
