version: '3.4'

services:
    preprocess:
        image: ankurgos/ingest:3.0
        environment:
            - NUM_PROCESSES
        volumes:
            - ${TRAIN_DIR}:/data/train
            - ${VAL_DIR}:/data/val
        command: "python -m ingest.preprocess_for_training"

    train:
        image: ankurgos/train_detect:1.0
        ipc: host
        volumes:
            - ${TRAIN_DIR}:/data/train
            - ${VAL_DIR}:/data/val
            - ${WEIGHTS_DIR}:/data/weights
            - ${TENSORBOARD_LOGDIR}:/app/runs
        ports:
            - 8008:8008
        command: "/bin/sh -c ./train.sh"


