version: "3"

networks:
  default:
    external:
      name: cosmos_swarm_network 

services:
    aggregate_sections:
        image: uwcosmos/aggregate_sections:latest
        command: "python3 -m agg.aggregate"
        environment:
            - DATASET_ID
            - MYSQL_USER
            - MYSQL_PASSWORD
            - MYSQL_HOST
            - MYSQL_PORT

    extract_tables:
        image: uwcosmos/extract_tables:latest
        ipc: host
        command: "python3 -m tableextractions.pdf_table_extractions"
        volumes:
            - ${DIR}:/input
        environment:
            - DATASET_ID
            - MYSQL_USER
            - MYSQL_PASSWORD
            - MYSQL_HOST
            - MYSQL_PORT
