version: "2.3"
services:
    torch_model:
        build: .
        runtime: nvidia
        ipc: host
        volumes:
            - .:/vol/
    redis:
      image: "redis:alpine"
      volumes:
        - ./redis_data:/data
      restart: always
      ports:
        - "6379:6379"

    cosmos_postgres:
        image: postgres:10.5-alpine
        environment:
            - POSTGRES_DB=cosmos
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
        ports:
            - 54321:5432
    
