version: '3.4'

networks:
    swarm_network:
        driver: overlay
        attachable: true

services:
    adminer:
        image: adminer
        ports:
            - 8080:8080
        networks:
            swarm_network:

    ingestion:
#        image: iaross/ingestion_test_dummy:latest
        image: uwcosmos/ingestion_dev:latest
        networks:
            swarm_network:
        environment:
            - MYSQL_USER
            - MYSQL_PASSWORD
            - MYSQL_HOST
            - MYSQL_PORT
            - DEVICE=cpu
            - PYTHONUNBUFFERED=TRUE
        command: "gunicorn -w 4 -b 0.0.0.0:8000 ingest.app"
        depends_on:
            - scheduler
            - worker1
            - worker2
        ports:
            - 8000:8000

    scheduler:
#        image: iaross/ingestion_test_dummy:latest
        image: uwcosmos/ingestion_dev:latest
        networks:
            swarm_network:
        command: "dask-scheduler"
        ports:
            - 8787:8787

    worker1:
#        image: iaross/ingestion_test_dummy:latest
        image: uwcosmos/ingestion_dev:latest
        networks:
            swarm_network:
        environment:
            - MYSQL_USER
            - MYSQL_PASSWORD
            - MYSQL_HOST
            - MYSQL_PORT
            - CUDA_VISIBLE_DEVICES=''
        command: "dask-worker tcp://scheduler:8786 --nprocs 15 --resources 'process=1' --preload ingest.process_setup"
        volumes:
            - ${TMP_DIR}:/tmp
        depends_on:
            - scheduler

    worker2:
#        image: iaross/ingestion_test_dummy:latest
        image: uwcosmos/ingestion_dev:latest
        networks:
            swarm_network:
        environment:
            - MYSQL_USER
            - MYSQL_PASSWORD
            - MYSQL_HOST
            - MYSQL_PORT
            - DEVICE=cuda:0
            - CUDA_VISIBLE_DEVICES=0
        command: "dask-worker tcp://scheduler:8786 --nprocs 1 --resources 'GPU=1' --preload ingest.detect_setup"
        depends_on:
            - scheduler

