BACKBONE: "resnet101"
HEAD_DIM: 1024
PROPOSAL_METHOD: "CONNECTED_COMPONENTS"
WARPED_SIZE: 250
EXPANSION_DELTA: 100
CLASSES: ["Section Header", "Body Text", "Figure", "Figure Caption", "Table", "Equation",
      "Page Footer", "Page Header", "Table Caption", "Table Note", "Abstract", "Other", "Equation label", "Reference text", "Figure Note"]
TRAINING: False
