version: "3.4"
services:
    lm:
        build: .
        #image: reflex:latest
        ipc: host
        volumes:
            - ./reflex.py:/reflex.py/
            - ./src/:/src/
            - ./data:/data/
            - ./tests:/tests/
        working_dir: /kbc

