LEARNING_RATE: 
   TYPE: "float"
   MIN: 0.0001
   MAX: 0.005 
WEIGHT_DECAY:
  TYPE: "FLOAT"
  MIN: 0.0001
  MAX: 0.01
BATCH_SIZE: 
  TYPE: "int"
  MIN: 10
  MAX: 12
EPOCHS: 
  TYPE: "int"
  MIN: 30
  MAX: 60
HEAD_DIM: 
  TYPE: "int"
  MIN: 512
  MAX: 2000

