version: "2.3"
services:
    aggregate_sections:
        build: .
        ipc: host
        volumes:
            - .:/develop/
        command: "tail -F /dev/null"
        environment:
            - DBCONNECT
        
        

